### ISSUE TITLE
The official Anghami desktop client is already there. 

### ISSUE THREAD

**Issue by Almo7aya** [ahmed-shehata/anghami-desktop#1]
Hello, I found the official Anghami desktop client you can find it here
https://www.npmjs.com/package/anghami

If you are interested in Anghami stuff you can check my project 
https://github.com/almo7aya/anghamify

**Comment by ahmed-shehata** [comment]
not official, not maintained, not open source.

**Comment by Almo7aya** [comment]
The first link is the official desktop version, yes it's not open source and not updated in npm, read the package.json of the package and you will know some thing.

**Comment by ahmed-shehata** [comment]
Since it's **not maintained** and **not open source**, and also does not actually work (too outdated to start)

Thanks for your contribution though, this project is aimed to provide an **Unofficial** client for Anghami as mentioned in the [README](https://github.com/ahmed-shehata/anghami-desktop/blob/master/README.md).
